// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKHKhpWw48FUpoWeezPC9sknFjYu7tvfY',
    appId: '1:625042287788:web:25201a363d2fb0d7c70309',
    messagingSenderId: '625042287788',
    projectId: 'my-nutrition-appliction',
    authDomain: 'my-nutrition-appliction.firebaseapp.com',
    storageBucket: 'my-nutrition-appliction.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIDCN39dD22FUqlUatMGsvHioBo0Yufu0',
    appId: '1:625042287788:android:ea664967ed06af12c70309',
    messagingSenderId: '625042287788',
    projectId: 'my-nutrition-appliction',
    storageBucket: 'my-nutrition-appliction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDNfZoGcBfmFy4px4i0RKnjHFNKO8jGBM',
    appId: '1:625042287788:ios:f1319340273db426c70309',
    messagingSenderId: '625042287788',
    projectId: 'my-nutrition-appliction',
    storageBucket: 'my-nutrition-appliction.appspot.com',
    iosClientId: '625042287788-nqbumb0tnjc8nbidmm6n0ufjfdfgdemr.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );
}
