// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXO0OmpbCusGWJbiydG4lXiMjXIGRAfVg',
    appId: '1:27571610992:web:977e80795a8d4e56c11bb5',
    messagingSenderId: '27571610992',
    projectId: 'nutrition-app-fc942',
    authDomain: 'nutrition-app-fc942.firebaseapp.com',
    storageBucket: 'nutrition-app-fc942.appspot.com',
    measurementId: 'G-6XJ1LD6WLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEoMPsHU2lFV58k-QS0Ko4lQp4frVS0UI',
    appId: '1:27571610992:android:c90894defea0f7ffc11bb5',
    messagingSenderId: '27571610992',
    projectId: 'nutrition-app-fc942',
    storageBucket: 'nutrition-app-fc942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjDPIs_nMG977SiEfwKsBSy30YUL-dUw',
    appId: '1:27571610992:ios:5d2ecdbe9b58a7aac11bb5',
    messagingSenderId: '27571610992',
    projectId: 'nutrition-app-fc942',
    storageBucket: 'nutrition-app-fc942.appspot.com',
    iosClientId: '27571610992-homh180vnsbddtci3jo4clnb1eatv73m.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );
}
